import React from 'react';
import { Shield, Lock, Eye, CheckCircle2, UserCheck, Database, FileText } from 'lucide-react';

export const PrivacyModalContent: React.FC = () => {
  return (
    <div className="space-y-6 text-xs text-slate-700 dark:text-slate-200 leading-relaxed font-sans max-h-[75vh] overflow-y-auto pr-2" id="privacy_modal_content">
      {/* Header */}
      <div className="border-b border-slate-200 dark:border-slate-800 pb-3">
        <span className="bg-emerald-100 text-emerald-800 dark:bg-emerald-950/80 dark:text-emerald-300 px-2.5 py-0.5 rounded-full text-[10px] font-bold tracking-wider uppercase font-mono">
          ODPC Certified • Kenya Data Protection Act 2019
        </span>
        <h4 className="font-extrabold text-slate-900 dark:text-white text-lg mt-2 font-display">
          Privacy Policy & Data Protection Charter
        </h4>
        <p className="text-xs text-slate-500 dark:text-slate-400 mt-1">
          Registration Certificate No: ODPC/REG/KEN/2026/0842 | Last Updated: September 2026
        </p>
      </div>

      {/* Overview */}
      <div className="p-3.5 bg-slate-50 dark:bg-slate-850 rounded-xl border border-slate-200 dark:border-slate-800 text-[11.5px] space-y-2">
        <p className="font-semibold text-slate-900 dark:text-white">
          COMMITMENT TO DATA SOVEREIGNTY & PRIVACY
        </p>
        <p className="text-slate-600 dark:text-slate-300">
          ShambaLoop Agricultural Cooperative ("ShambaLoop", "we", "us") values the sanctity and confidentiality of data generated by Kenyan farmers, landowners, investors, and veterinary practitioners. We process personal and agronomic data strictly in conformity with the <strong>Kenya Data Protection Act of 2019</strong>, the Data Protection (General) Regulations 2021, and the African Union Malabo Convention on Cyber Security and Personal Data Protection.
        </p>
      </div>

      {/* 1. Data Categories */}
      <div className="space-y-2">
        <h5 className="font-bold text-slate-900 dark:text-white text-xs uppercase tracking-wider flex items-center gap-2">
          <Database className="w-3.5 h-3.5 text-emerald-600" />
          1. Categories of Data Collected & Processed
        </h5>
        <div className="space-y-2 text-slate-600 dark:text-slate-300 text-[11px] pl-2">
          <div className="p-2.5 rounded-lg bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800">
            <strong className="text-slate-800 dark:text-white block text-xs font-semibold">a. Identity & KYC Credentials</strong>
            <p className="mt-0.5">Full legal names, National Identity Card (ID) or Passport numbers, KRA PIN certificates, passport-style profile photographs, and mobile telephone numbers utilized for two-factor authentication (2FA) and M-Pesa settlements.</p>
          </div>
          <div className="p-2.5 rounded-lg bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800">
            <strong className="text-slate-800 dark:text-white block text-xs font-semibold">b. Cadastral & Agronomic Information</strong>
            <p className="mt-0.5">GPS polygon coordinates of farms, Land Registry Title Deed serials, Registry Map Sheets (FRM), soil pH test analyses, water availability metrics, and altitude telemetry.</p>
          </div>
          <div className="p-2.5 rounded-lg bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800">
            <strong className="text-slate-800 dark:text-white block text-xs font-semibold">c. Livestock Clinical Health & Production Logs</strong>
            <p className="mt-0.5">Ear-tag numbers, bovine pedigree genealogies, daily milking logs (morning and evening volumes in Liters), veterinary treatment history, vaccination dates, and clinical audit photographs.</p>
          </div>
          <div className="p-2.5 rounded-lg bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800">
            <strong className="text-slate-800 dark:text-white block text-xs font-semibold">d. Escrow & Financial Records</strong>
            <p className="mt-0.5">Safaricom Daraja transaction IDs, escrow milestone releases, dividend allocations, cooperative dues, and wallet balances.</p>
          </div>
        </div>
      </div>

      {/* 2. Lawful Grounds */}
      <div className="space-y-2">
        <h5 className="font-bold text-slate-900 dark:text-white text-xs uppercase tracking-wider flex items-center gap-2">
          <FileText className="w-3.5 h-3.5 text-emerald-600" />
          2. Lawful Bases for Data Processing
        </h5>
        <ul className="space-y-1.5 text-slate-600 dark:text-slate-300 text-[11px] pl-2 list-disc ml-3">
          <li><strong>Contractual Performance:</strong> Processing is essential to execute tripartite farming leases, release escrow funds, and deliver livestock health alerts.</li>
          <li><strong>Statutory Compliance:</strong> Meeting legal mandates under the Kenya Land Act, Cooperative Societies Act (Cap 490), and Anti-Money Laundering (AML/CFT) regulations enforced by the Financial Reporting Centre (FRC).</li>
          <li><strong>Legitimate Interests:</strong> Preventing agricultural fraud, verifying cattle health traceability, and safeguarding platform stability.</li>
        </ul>
      </div>

      {/* 3. Data Protection Rights */}
      <div className="space-y-2">
        <h5 className="font-bold text-slate-900 dark:text-white text-xs uppercase tracking-wider flex items-center gap-2">
          <UserCheck className="w-3.5 h-3.5 text-emerald-600" />
          3. Your Statutory Rights Under the Data Protection Act
        </h5>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-2 text-[11px]">
          <div className="p-2.5 rounded-lg bg-emerald-50/50 dark:bg-emerald-950/20 border border-emerald-100 dark:border-emerald-900/40">
            <span className="font-bold text-emerald-900 dark:text-emerald-300 block">Right of Access & Portability</span>
            <p className="text-slate-600 dark:text-slate-300 text-[10.5px]">Request a machine-readable copy of your farm yields, contracts, and financial statements at any time.</p>
          </div>
          <div className="p-2.5 rounded-lg bg-emerald-50/50 dark:bg-emerald-950/20 border border-emerald-100 dark:border-emerald-900/40">
            <span className="font-bold text-emerald-900 dark:text-emerald-300 block">Right to Rectification</span>
            <p className="text-slate-600 dark:text-slate-300 text-[10.5px]">Correct incomplete or inaccurate title deed indices, telephone details, or livestock records.</p>
          </div>
          <div className="p-2.5 rounded-lg bg-emerald-50/50 dark:bg-emerald-950/20 border border-emerald-100 dark:border-emerald-900/40">
            <span className="font-bold text-emerald-900 dark:text-emerald-300 block">Right to Erasure (To be Forgotten)</span>
            <p className="text-slate-600 dark:text-slate-300 text-[10.5px]">Request deletion of your account, subject to mandatory 7-year statutory financial retention under Kenya tax law.</p>
          </div>
          <div className="p-2.5 rounded-lg bg-emerald-50/50 dark:bg-emerald-950/20 border border-emerald-100 dark:border-emerald-900/40">
            <span className="font-bold text-emerald-900 dark:text-emerald-300 block">Right to Object & Restrict</span>
            <p className="text-slate-600 dark:text-slate-300 text-[10.5px]">Opt out of non-essential marketing telemetry or algorithmic profile scoring.</p>
          </div>
        </div>
      </div>

      {/* Contact DPO */}
      <div className="p-3 bg-slate-100 dark:bg-slate-800 rounded-xl border border-slate-200 dark:border-slate-700 text-[11px] text-slate-600 dark:text-slate-300 space-y-1">
        <strong className="block text-slate-900 dark:text-white font-bold text-xs uppercase tracking-wider">
          Data Protection Officer (DPO) Contact
        </strong>
        <p>
          For privacy inquiries, rights enforcement, or ODPC complaints: Email: <span className="font-mono text-emerald-600 dark:text-emerald-400 font-semibold">dpo@shambaloop.com</span> | Telephone: +254 728 606 684 | Physical Address: ShambaLoop Hub, Milimani Estate, Kisumu, Kenya.
        </p>
      </div>
    </div>
  );
};
