import React from 'react';
import { Database, Lock, UserCheck } from 'lucide-react';

const Section: React.FC<{ title: string; children: React.ReactNode }> = ({ title, children }) => (<section className="space-y-1.5"><h5 className="font-bold text-slate-900 dark:text-white text-xs uppercase tracking-wider">{title}</h5><div className="space-y-1.5 text-slate-600 dark:text-slate-300 text-[11px]">{children}</div></section>);

export const PrivacyModalContent: React.FC = () => (
  <div className="space-y-6 text-xs text-slate-700 dark:text-slate-200 leading-relaxed font-sans max-h-[75vh] overflow-y-auto pr-2" id="privacy_modal_content">
    <header className="border-b border-slate-200 dark:border-slate-800 pb-3"><span className="bg-emerald-100 text-emerald-800 dark:bg-emerald-950/80 dark:text-emerald-300 px-2.5 py-0.5 rounded-full text-[10px] font-bold tracking-wider uppercase font-mono">Privacy notice</span><h4 className="font-extrabold text-slate-900 dark:text-white text-lg mt-2 font-display">Privacy Policy &amp; Data Protection Charter</h4><p className="text-xs text-slate-500 dark:text-slate-400 mt-1">Effective: 19 September 2026 · Version SL-PRIVACY-1.0</p></header>
    <div className="p-3.5 bg-slate-50 dark:bg-slate-850 rounded-xl border border-slate-200 dark:border-slate-800 text-[11.5px] space-y-2"><p className="font-semibold text-slate-900 dark:text-white">OUR PRIVACY COMMITMENT</p><p className="text-slate-600 dark:text-slate-300">ShambaLoop processes personal data to run the marketplace and role-based workspaces. We aim to process it lawfully, fairly, transparently, and only for specified purposes. This notice is designed to support the Kenya Data Protection Act of 2019 and applicable regulations; it does not claim a certification or registration status.</p></div>
    <Section title="1. Who this notice covers and how to contact us"><p>This policy applies to visitors, account holders, applicants, farmers, landowners, investors, veterinarians, administrators, and people whose information is included in evidence submitted to the platform. The controller for the relevant platform processing is ShambaLoop, unless an opportunity-specific agreement identifies another controller.</p><p><strong>Data Protection Officer (DPO) Contact:</strong> send privacy requests or questions to <span className="font-semibold text-emerald-600 dark:text-emerald-400">privacy@shambaloop.com</span>. Do not include passwords, M-Pesa PINs, or full identity-document images in a standard email. We may need to verify your identity before acting on a request.</p></Section>
    <Section title="2. Data we collect"><p>Account and contact data can include name, mobile number, email address, account role, county, profile image, and authentication or account-recovery events. Verification submissions may include identity, professional, business, property, and authority-to-act documents.</p><p>Operational data can include listings, farm or livestock details, production and veterinary records, photographs, messages, reviews, dispute evidence, and agreement metadata. Payment workflow data can include transaction references, amounts, dates, status, and provider responses; we do not ask you to send payment PINs to us.</p><p>Technical data can include IP address, browser and device information, application logs, security events, and local storage needed to maintain a session or preference. We may also receive information from payment providers, professional registries, counterparties, or public sources where lawful and necessary for verification or fraud prevention.</p></Section>
    <Section title="3. Why we use data and our legal bases"><p>We use data to create and secure accounts; provide dashboards; verify participants and listings; enable requests, records, communications, disputes, payments, and support; prevent fraud and abuse; meet recordkeeping obligations; and improve reliability and accessibility.</p><p>Depending on the activity, our basis may be performance of a contract or pre-contract request, compliance with a legal obligation, legitimate interests such as security and service integrity, protection of vital interests where applicable, or consent. Where consent is the basis, you may withdraw it, although this will not affect prior lawful processing or processing needed on another lawful basis.</p></Section>
    <Section title="4. Sensitive data and verification documents"><p>Identity, property, financial, and health-related information may be sensitive personal data under Kenyan law. We limit access to authorised people and systems, use it for stated verification, safety, transaction, and compliance purposes, and seek an appropriate lawful basis or consent where required.</p><p>Do not upload another person’s document, health information, or photograph unless you have authority and have provided any required notice. If a document is not required for the requested feature, redact unnecessary information before submitting it.</p></Section>
    <Section title="5. Sharing and disclosures"><p>We share data only as needed with authorised counterparties to an opportunity, service providers that help operate the platform, payment providers, professional advisers, and public authorities where legally required or necessary to protect rights, safety, or the platform. Role-based access is intended to limit each user to relevant data.</p><p>Service providers must process data under appropriate instructions and safeguards. We do not sell personal data. We do not disclose private verification documents or health records to general marketplace visitors.</p></Section>
    <Section title="6. International transfers, security, and retention"><p>If data is processed outside Kenya, we will use an applicable transfer mechanism, consent, or adequate safeguards as required by law. No security system is perfect; protect your password, sign out of shared devices, and promptly report suspected account compromise.</p><p>We retain data only as long as necessary for the purpose collected, service continuity, disputes, security, accounting, legal obligations, and legitimate claims. We then delete, anonymise, or securely archive it in accordance with applicable retention requirements and our operational controls.</p></Section>
    <Section title="7. Your rights and choices"><p>Subject to applicable law, you may ask to be informed about processing, access data we hold about you, correct inaccurate or misleading data, object to certain processing, request deletion of false or misleading data, or make a complaint. Some requests may be limited where we must retain data, protect another person’s rights, prevent fraud, or comply with law.</p><p>To exercise a right, write to privacy@shambaloop.com with the request, relevant account details, and a safe way for us to contact you. We will explain the verification and response process and may ask for clarification where necessary.</p></Section>
    <Section title="8. Children, automated activity, and marketing"><p>The platform is not intended for people who cannot lawfully enter the required agreements. If we learn that personal data was provided without appropriate authority, we will take reasonable steps to review and address it.</p><p>We may use rules and alerts to detect anomalies, security risks, incomplete records, or workflow status. These tools assist operations; they should not be treated as the sole basis for a significant decision without appropriate review. Marketing communications include an opt-out method where required.</p></Section>
    <Section title="9. Changes and complaints"><p>We may update this notice when our processing, service, or legal obligations change. The current version and effective date will be shown here. If you are dissatisfied with our response, you may have the right to raise a complaint with the Office of the Data Protection Commissioner or another competent authority.</p></Section>
    <div className="grid grid-cols-1 sm:grid-cols-3 gap-2 text-[10.5px]"><div className="p-2.5 rounded-lg bg-emerald-50 dark:bg-emerald-950/20 border border-emerald-100 dark:border-emerald-900/40"><Database className="w-4 h-4 text-emerald-600 mb-1" /><strong>Data minimisation</strong><p>Collect only what a feature or obligation needs.</p></div><div className="p-2.5 rounded-lg bg-emerald-50 dark:bg-emerald-950/20 border border-emerald-100 dark:border-emerald-900/40"><Lock className="w-4 h-4 text-emerald-600 mb-1" /><strong>Controlled access</strong><p>Private records are restricted by role and purpose.</p></div><div className="p-2.5 rounded-lg bg-emerald-50 dark:bg-emerald-950/20 border border-emerald-100 dark:border-emerald-900/40"><UserCheck className="w-4 h-4 text-emerald-600 mb-1" /><strong>Your rights</strong><p>Ask about, access, correct, or object to processing.</p></div></div>
  </div>
);
