import React, { useEffect, useMemo, useState } from 'react';
import type { LivestockPartnership, User } from '../types';
import { sharedWorkspaceApi } from '../services/sharedWorkspaceService';

type Mode = 'fms' | 'wallet' | 'disputes' | 'reviews';
export default function ParticipantWorkspace({ user, partnerships, mode }: { user: User; partnerships: LivestockPartnership[]; mode: Mode }) {
  const [records, setRecords] = useState<any[]>([]), [documents, setDocuments] = useState<any[]>([]), [wallet, setWallet] = useState<any>(), [disputes, setDisputes] = useState<any[]>([]), [reviews, setReviews] = useState<any>(), [eligible, setEligible] = useState<any[]>([]), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  const participantFarmIds = useMemo(() => Array.from(new Set(partnerships.map(p => `farm_${p.farmerId}`))), [partnerships]);
  const load = async () => { setError(''); if (mode === 'fms') { const recordsResult = await sharedWorkspaceApi.records(); const docResults = await Promise.all(participantFarmIds.map(id => sharedWorkspaceApi.documents(id))); if (recordsResult.data) setRecords(recordsResult.data); setDocuments(docResults.flatMap(r => r.data || [])); if (recordsResult.error || docResults.some(r => r.error)) setError(recordsResult.error || docResults.find(r => r.error)?.error || 'Unable to load farm management records.'); } if (mode === 'wallet') { const r = await sharedWorkspaceApi.wallet(); if (r.data) setWallet(r.data); else setError(r.error || 'Unable to load wallet.'); } if (mode === 'disputes') { const r = await sharedWorkspaceApi.disputes(); if (r.data) setDisputes(r.data); else setError(r.error || 'Unable to load disputes.'); } if (mode === 'reviews') { const [r, e] = await Promise.all([sharedWorkspaceApi.reviews(), sharedWorkspaceApi.eligibleReviews()]); if (r.data) setReviews(r.data); if (e.data) setEligible(e.data); if (r.error || e.error) setError(r.error || e.error || 'Unable to load reviews.'); } };
  useEffect(() => { void load(); }, [mode, user.id, participantFarmIds.join(':')]);
  const act = async (fn: () => Promise<void>) => { setBusy(true); setError(''); try { await fn(); await load(); } catch (e: any) { setError(e.message || 'Action could not be completed.'); } finally { setBusy(false); } };
  if (mode === 'fms') return <Panel title="Farm Management System"><p>Authorized daily farm, veterinary, receipt, photo, and event records. Downloads are access-controlled by the farm relationship.</p><Section title="Farm activity and reports" rows={records.map(r => `${r.recordType} · ${r.description} · ${r.date}`)} empty="No authorized farm records."/><Section title="Authorized documents" rows={documents.map(d => <a className="text-emerald-700 underline" href={d.url}>{d.documentType} · {d.originalName} · {new Date(d.createdAt).toLocaleDateString()}</a>)} empty="No authorized documents."/>{error && <Error value={error}/>}</Panel>;
  if (mode === 'wallet') return <Panel title="Wallet"><p>All balances and transaction states are calculated by the server ledger.</p><div className="grid grid-cols-2 gap-3"><Metric label="Available" value={`KES ${(wallet?.availableBalanceKES || 0).toLocaleString()}`}/><Metric label="Returns / earnings" value={`KES ${((wallet?.returnsKES || wallet?.earningsKES || wallet?.farmerEarningsKES) || 0).toLocaleString()}`}/></div><form className="mt-3 flex gap-2" onSubmit={e => { e.preventDefault(); const amount = Number(new FormData(e.currentTarget).get('amount')); void act(async () => { const r = await sharedWorkspaceApi.depositIntent(amount, crypto.randomUUID()); if (r.error) throw new Error(r.error); e.currentTarget.reset(); }); }}><input required name="amount" type="number" min="100" placeholder="Feed funding amount (KES)"/><button disabled={busy} className="action-primary">Create payment intent</button></form><Section title="Transaction history" rows={(wallet?.recentTransactions || []).map((t: any) => `${t.reference} · ${t.type} · KES ${t.amountKES.toLocaleString()} · ${t.status} · ${t.description}`)} empty="No transactions."/><Error value={error}/></Panel>;
  if (mode === 'disputes') { const partnership = partnerships[0]; const counterpart = user.role === 'investor' ? partnership?.farmerId : partnership?.investorId; return <Panel title="Dispute Room"><p>Cases include issues raised by you, against you, active cases, and resolved outcomes.</p>{partnership && counterpart ? <form className="mt-3 space-y-2" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); void act(async () => { const r = await sharedWorkspaceApi.raiseDispute({ respondentId: counterpart, partnershipId: partnership.id, title: f.get('title'), reason: f.get('reason') }); if (r.error) throw new Error(r.error); e.currentTarget.reset(); }); }}><input required name="title" placeholder="Issue title"/><textarea required name="reason" placeholder="Issue, evidence summary, and requested outcome"/><button disabled={busy} className="action-primary">Raise dispute</button></form> : <p>No linked partnership is available for a new case.</p>}<Section title="Your cases" rows={disputes.map(d => `${d.title} · ${d.status} · ${d.resolutionNotes || d.reason}`)} empty="No disputes involving your account."/><Error value={error}/></Panel>; }
  return <Panel title="Reviews"><p>Only completed, server-validated engagements can be reviewed.</p>{eligible[0] && <form className="mt-3 space-y-2" onSubmit={e => { e.preventDefault(); const form = new FormData(e.currentTarget), target = eligible.find(x => x.id === form.get('target')); void act(async () => { const r = await sharedWorkspaceApi.submitReview({ targetUserId: target.id, rating: Number(form.get('rating')), comment: form.get('comment'), [target.engagementType === 'job' ? 'jobId' : 'partnershipId']: target.engagementId }); if (r.error) throw new Error(r.error); e.currentTarget.reset(); }); }}><select name="target">{eligible.map(x => <option value={x.id}>{x.name} · {x.context}</option>)}</select><select name="rating"><option value="5">5 stars</option><option value="4">4 stars</option><option value="3">3 stars</option><option value="2">2 stars</option><option value="1">1 star</option></select><textarea required name="comment" placeholder="Professional factual review"/><button disabled={busy} className="action-primary">Submit review</button></form>}<Section title={`Reviews received · ${reviews?.averageRating ?? '—'} average`} rows={(reviews?.received || []).map((r: any) => `${r.rating}/5 · ${r.comment}`)} empty="No reviews received."/><Section title="Reviews submitted" rows={(reviews?.written || []).map((r: any) => `${r.targetUserName} · ${r.rating}/5 · ${r.comment}`)} empty="No reviews submitted."/><Error value={error}/></Panel>;
}
function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <section className="space-y-3 rounded-xl border border-slate-200 bg-white p-4 text-xs dark:border-slate-800 dark:bg-slate-900"><h3 className="text-sm font-bold dark:text-white">{title}</h3>{children}</section>; }
function Section({ title, rows, empty }: { title: string; rows: React.ReactNode[]; empty: string }) { return <section><strong>{title}</strong>{rows.length ? <ul className="mt-2 divide-y dark:divide-slate-800">{rows.map((row, index) => <li key={index} className="py-2">{row}</li>)}</ul> : <p className="mt-2 text-slate-500">{empty}</p>}</section>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded border p-3"><span className="text-slate-500">{label}</span><strong className="block text-sm dark:text-white">{value}</strong></div>; }
const Error: React.FC<{ value: string }> & { new(message?: string): globalThis.Error } = function Error(this: unknown, arg: { value: string } | string) {
  if (typeof arg === 'string') return new globalThis.Error(arg) as any;
  return arg.value ? <p className="text-rose-700">{arg.value}</p> : null;
} as any;
